# LLM model
api_key: ""
model_id: "deepseek-chat"
temperature: 1.0

# TritonBench
statis_path: "./TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
py_folder: "./TritonBench/data/TritonBench_G_v1"
instruction_path: "./TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
corpus_path: "./dataloaders/TB_eval/train_crawl.json"
golden_metrics: "./TritonBench/performance_metrics/perf_G/golden_metrics"
perf_ref_folder: null
perf_G_path: "./TritonBench/performance_metrics/perf_G"
py_interpreter: "python"
result_path: null
mem_file: null
start_iter: 0
datalen: null
start_idx: 0
target_kernels: ["layernorm_fwd_triton.py"]

# agent
output_path: "../outputs/layernorm_fwd_triton.jsonl"
max_iteration: 20
multi_thread: true
ancestor_num: 5